### ISSUE TITLE
Can we have the same for Android

### ISSUE THREAD

**Issue by Hisaack** [digitallysavvy/AR-Remote-Support#11]
Hello, when are you going to release it for Android using ARCore?

**Comment by digitallysavvy** [comment]
One of my colleagues has been working on the ARCore example. Here is the repo: https://github.com/ysc1995/ARCoreAgora

**Comment by Mugambi-Ian** [comment]
Hello, Thanks for sharing, currently am looking for ARCore supported device. But the repo you shared doesn't have instructions yet. Is the project complete? Also, is it working just like the one you discussed on your article?

**Comment by Hisaack** [comment]
Yea.. Thats what I was about to ask too :)

**Comment by digitallysavvy** [comment]
My colleague is working on the tutorial and instructions. I have shared the repo in an effort to provide you with the code in a timely manner. This is not my project so I can not make promises as to delivery dates. Feel free to raise issues on that repo. 

With regard to functionality it is not 1:1 feature parity because he chose to take a different approach than myself. But it should provide the core principles to build your own version.
